# Generated by Django 6.1 on 2026-08-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentonboarding",
            name="region",
            field=models.CharField(
                choices=[
                    ("IN-WEST", "India West"),
                    ("IN-EAST", "India East"),
                    ("IN-NORTH", "India North"),
                    ("IN-SOUTH", "India South"),
                ],
                max_length=10,
            ),
        ),
    ]
